/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// This checked-in copy is updated so the new routes are available immediately;
// the TanStack Router plugin may regenerate it during development.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StockSymbolRouteImport } from './routes/stock.$symbol'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as StockChatRouteImport } from './routes/stock-chat'
import { Route as StockChatSymbolRouteImport } from './routes/stock-chat.$symbol'
import { Route as ResearchHistoryRouteImport } from './routes/research-history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StockSymbolRoute = StockSymbolRouteImport.update({
  id: '/stock/$symbol',
  path: '/stock/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const StockChatRoute = StockChatRouteImport.update({
  id: '/stock-chat',
  path: '/stock-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const StockChatSymbolRoute = StockChatSymbolRouteImport.update({
  id: '/stock-chat/$symbol',
  path: '/stock-chat/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchHistoryRoute = ResearchHistoryRouteImport.update({
  id: '/research-history',
  path: '/research-history',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stock/$symbol': typeof StockSymbolRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/stock-chat': typeof StockChatRoute
  '/stock-chat/$symbol': typeof StockChatSymbolRoute
  '/research-history': typeof ResearchHistoryRoute
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/stock/$symbol': typeof StockSymbolRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/stock-chat': typeof StockChatRoute
  '/stock-chat/$symbol': typeof StockChatSymbolRoute
  '/research-history': typeof ResearchHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/stock/$symbol' | '/ai-assistant' | '/stock-chat' | '/stock-chat/$symbol' | '/research-history'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/stock/$symbol' | '/ai-assistant' | '/stock-chat' | '/stock-chat/$symbol' | '/research-history'
  id: '__root__' | '/' | '/stock/$symbol' | '/ai-assistant' | '/stock-chat' | '/stock-chat/$symbol' | '/research-history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StockSymbolRoute: typeof StockSymbolRoute
  AiAssistantRoute: typeof AiAssistantRoute
  StockChatRoute: typeof StockChatRoute
  StockChatSymbolRoute: typeof StockChatSymbolRoute
  ResearchHistoryRoute: typeof ResearchHistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/$symbol': {
      id: '/stock/$symbol'
      path: '/stock/$symbol'
      fullPath: '/stock/$symbol'
      preLoaderRoute: typeof StockSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-chat': {
      id: '/stock-chat'
      path: '/stock-chat'
      fullPath: '/stock-chat'
      preLoaderRoute: typeof StockChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-chat/$symbol': {
      id: '/stock-chat/$symbol'
      path: '/stock-chat/$symbol'
      fullPath: '/stock-chat/$symbol'
      preLoaderRoute: typeof StockChatSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-history': {
      id: '/research-history'
      path: '/research-history'
      fullPath: '/research-history'
      preLoaderRoute: typeof ResearchHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  StockSymbolRoute,
  AiAssistantRoute,
  StockChatRoute,
  StockChatSymbolRoute,
  ResearchHistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
